-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 17:22:01 2022
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vivero13
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vivero13
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vivero13` ;
USE `vivero13` ;

-- -----------------------------------------------------
-- Table `vivero13`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero13`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero13`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero13`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero13`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero13`.`order` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vivero13`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero13`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero13`.`order_item` (
  `order_itemt_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`order_itemt_id`, `order_id`, `product_id`),
  INDEX `fk_sales_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_sales_has_products_sales1_idx` (`order_id` ASC),
  UNIQUE INDEX `order_details_id_UNIQUE` (`order_itemt_id` ASC),
  CONSTRAINT `fk_sales_has_products_sales1`
    FOREIGN KEY (`order_id`)
    REFERENCES `vivero13`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `vivero13`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) 
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero13`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero13`.`transaction` (
  `order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `user_id`),
  INDEX `fk_transaction_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_transaction_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `vivero13`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vivero13`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
